-- Base PostgreSQL seed. Re-runnable: it drops the demo tables and recreates them.
DROP TABLE IF EXISTS
    integrationauditevents,
    attendancedeliveryattempts,
    attendancebatchentries,
    attendancebatches,
    attendancemarks,
    externalentitymappings,
    integrationconnections,
    classroommemberships,
    classroomstudents,
    ownedshopitems,
    avatarconfigs,
    transactions,
    attendancerecords,
    weeklyassignmenttemplates,
    schedule,
    shopitems,
    manualcoinadjustments,
    avatarbaseimages,
    users,
    classrooms,
    schools;

CREATE TABLE users (
    userid text PRIMARY KEY,
    name text NOT NULL,
    role text NOT NULL,
    email text NOT NULL,
    passwordhash text NOT NULL,
    classroomid text
);

CREATE TABLE classrooms (
    id text PRIMARY KEY,
    name text NOT NULL,
    teacherid text
);

CREATE TABLE classroomstudents (
    classroomid text NOT NULL,
    studentid text NOT NULL,
    PRIMARY KEY (classroomid, studentid)
);

CREATE TABLE shopitems (
    id text PRIMARY KEY,
    name text NOT NULL,
    price integer NOT NULL,
    description text NOT NULL
);

CREATE TABLE ownedshopitems (
    userid text NOT NULL,
    shopitemid text NOT NULL,
    PRIMARY KEY (userid, shopitemid)
);

CREATE TABLE avatarconfigs (
    userid text PRIMARY KEY,
    base text,
    hairstyle text,
    clothing text,
    accessory text
);

CREATE TABLE transactions (
    transactionid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userid text NOT NULL,
    amount integer NOT NULL,
    timestamp timestamp with time zone NOT NULL,
    description text NOT NULL
);

CREATE TABLE attendancerecords (
    userid text NOT NULL,
    classroomid text NOT NULL,
    presentdates text,
    absentdates text,
    PRIMARY KEY (userid, classroomid)
);

CREATE TABLE schedule (
    scheduleid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classroomid text NOT NULL,
    dayofweek text NOT NULL,
    starttime text NOT NULL,
    endtime text NOT NULL,
    doubleday boolean NOT NULL
);

INSERT INTO users (userid, name, role, email, passwordhash, classroomid) VALUES
('BenJam', 'Benjamin', 'student', 'BenJam@example.com', '$2a$10$CjkYbcz0E4nO5MvxiK4...oJGcCp5ndO0iQ5glmZo2ITGDtMKiZ8K', 'classroom1'),
('DHoney', 'Dylan Steenhoek', 'teacher', 'DHoney@example.com', '$2a$10$lSkGtrwXNpsriRUxhgGor.nLddrL0hiCjGtW/TEQ.NGC99j6xN5DW', ''),
('JRGRUNIG', 'Jed Grunig', 'teacher', 'jed@example.com', '$2a$10$89jnZG5yC7yjXyJEae/8xOiQ3PEP4HAtVc0gxKX6lqw6DCO7KNQqO', ''),
('PeteGrunigi', 'Peter Grunig', 'admin', 'petergrunig@gmail.com', '$2a$10$aGGj2pW8PFXJ/IjO0PESbe0rESTEnAopD9WYt.Qw25N/vg9vFVunq', ''),
('admin1', 'Demo Administrator', 'admin', 'admin@example.com', '$2a$10$j7TaLACJVyfoNgoiimtyy.b/PR.75ri.RZeEVoU.EBdyFHwjDwWxS', ''),
('jb', 'Joey', 'student', 'jb@example.com', '$2a$10$3fBFhi5ZfE4v7u/yehwR8uNqbqSY35PrYsnXxrYSV35ePJr5MunnC', 'classroom1'),
('sconner1', 'Seth Conner', 'student', 'sconner1@example.com', '$2a$10$ExSwVRKGZf99Q571Qe30Uuh/ecKQyupGFSqWfus2GiE0c8dejGXty', ''),
('student1', 'Demo Student', 'student', 'student@example.com', '$2a$10$j7TaLACJVyfoNgoiimtyy.b/PR.75ri.RZeEVoU.EBdyFHwjDwWxS', 'classroom1'),
('student2', 'Demo Student Two', 'student', 'student2@example.com', '$2a$10$j7TaLACJVyfoNgoiimtyy.b/PR.75ri.RZeEVoU.EBdyFHwjDwWxS', 'classroom2'),
('student3', 'Demo Student Three', 'student', 'student3@example.com', '$2a$10$j7TaLACJVyfoNgoiimtyy.b/PR.75ri.RZeEVoU.EBdyFHwjDwWxS', 'classroom2'),
('teacher1', 'Demo Teacher', 'teacher', 'teacher@example.com', '$2a$10$j7TaLACJVyfoNgoiimtyy.b/PR.75ri.RZeEVoU.EBdyFHwjDwWxS', ''),
('test', 'test2', 'teacher', 'hey@gmail.com', '$2a$10$GWPCqQ9BvUTWxFGNMYZhWOBl0v1m/9v0gfpajldzD4XsYhw6LJCYa', '');

INSERT INTO classrooms (id, name, teacherid) VALUES
('classroom1', 'Grade 1 - Room A', 'teacher1'),
('classroom2', 'Grade 5 - Room B', 'JRGRUNIG'),
('classroom3', 'Grade 2 - Room C', 'DHoney');

INSERT INTO classroomstudents (classroomid, studentid) VALUES
('classroom1', 'student1'),
('classroom1', 'jb'),
('classroom1', 'BenJam'),
('classroom2', 'student2'),
('classroom2', 'student3');

INSERT INTO shopitems (id, name, price, description) VALUES
('cape_gold', 'Golden Cape', 12, 'A shiny cape for extra style.'),
('glasses_rocket', 'Rocket Glasses', 10, 'A bold accessory for your avatar.'),
('hat_star', 'Star Hat', 5, 'A bright hat for a standout student.'),
('trail_rainbow', 'Rainbow Trail', 8, 'A colorful trail effect for your avatar.');

INSERT INTO ownedshopitems (userid, shopitemid) VALUES
('student1', 'hat_star');

INSERT INTO transactions (userid, amount, timestamp, description) VALUES
('student1', 1, '2026-06-09T15:33:47-06:00', 'Attendance reward'),
('student1', -5, '2026-06-09T16:29:38-06:00', 'Purchased Star Hat'),
('student1', 1, '2026-06-10T16:44:15-06:00', 'Attendance reward for 2026-06-10'),
('student1', 1, '2026-06-15T10:31:04-06:00', 'Attendance reward for 2026-06-15'),
('student1', 1, '2026-06-22T16:25:50-06:00', 'Attendance reward for 2026-06-22'),
('student1', 1, '2026-06-24T16:51:42-06:00', 'Attendance reward for 2026-06-24');

INSERT INTO attendancerecords (userid, classroomid, presentdates, absentdates) VALUES
('student1', 'classroom1', '["2026-06-09","2026-06-10","2026-06-15","2026-06-22","2026-06-24"]', NULL);
