-- Additive classroom prize catalog, redemption, and email outbox foundation.
-- Apply after Seed_DataBase3.sql before deploying the classroom prize store.
BEGIN;

CREATE TABLE IF NOT EXISTS classroomprizes (
    prizeid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classroomid text NOT NULL REFERENCES classrooms(id) ON UPDATE CASCADE,
    createdbyuserid text NOT NULL REFERENCES users(userid) ON UPDATE CASCADE,
    name text NOT NULL CHECK (char_length(btrim(name)) BETWEEN 1 AND 100),
    description text NOT NULL DEFAULT '' CHECK (char_length(description) <= 500),
    emoji text NOT NULL DEFAULT '' CHECK (char_length(emoji) <= 8),
    coinprice integer NOT NULL CHECK (coinprice BETWEEN 1 AND 10000),
    availablestock integer CHECK (availablestock BETWEEN 0 AND 10000),
    active boolean NOT NULL DEFAULT true,
    createdat timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedat timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS ix_classroomprizes_catalog
    ON classroomprizes (classroomid, active, name);

CREATE TABLE IF NOT EXISTS prizeredemptions (
    redemptionid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prizeid bigint NOT NULL REFERENCES classroomprizes(prizeid),
    classroomid text NOT NULL REFERENCES classrooms(id) ON UPDATE CASCADE,
    studentuserid text NOT NULL REFERENCES users(userid) ON UPDATE CASCADE,
    prizename text NOT NULL,
    prizeemoji text NOT NULL DEFAULT '',
    coinprice integer NOT NULL CHECK (coinprice BETWEEN 1 AND 10000),
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'fulfilled', 'canceled')),
    purchasetransactionid integer NOT NULL UNIQUE REFERENCES transactions(transactionid),
    refundtransactionid integer UNIQUE REFERENCES transactions(transactionid),
    purchasedat timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fulfilledat timestamptz,
    fulfilledbyuserid text REFERENCES users(userid) ON UPDATE CASCADE,
    canceledat timestamptz,
    canceledbyuserid text REFERENCES users(userid) ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_prizeredemptions_student
    ON prizeredemptions (studentuserid, purchasedat DESC);
CREATE INDEX IF NOT EXISTS ix_prizeredemptions_teacher_queue
    ON prizeredemptions (classroomid, status, purchasedat);

CREATE TABLE IF NOT EXISTS prizenotificationoutbox (
    notificationid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    redemptionid bigint NOT NULL REFERENCES prizeredemptions(redemptionid),
    recipientemail text NOT NULL,
    state text NOT NULL DEFAULT 'pending' CHECK (state IN ('pending', 'sending', 'sent', 'failed')),
    attemptcount integer NOT NULL DEFAULT 0 CHECK (attemptcount >= 0),
    nextattemptat timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lockedat timestamptz,
    lasterror text NOT NULL DEFAULT '',
    createdat timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sentat timestamptz,
    UNIQUE (redemptionid, recipientemail)
);
CREATE INDEX IF NOT EXISTS ix_prizenotificationoutbox_due
    ON prizenotificationoutbox (state, nextattemptat, notificationid);

COMMIT;
