//go:build integration

package store

import (
	"context"
	"database/sql"
	"errors"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/PeterGrunig/Attendance-HackDay/internal/domain"
	_ "github.com/lib/pq"
)

func TestPostgresPrizeMigrationAndLifecycle(t *testing.T) {
	databaseURL := os.Getenv("TEST_DATABASE_URL")
	if databaseURL == "" {
		t.Skip("TEST_DATABASE_URL is not configured")
	}
	db, err := sql.Open("postgres", databaseURL)
	if err != nil {
		t.Fatalf("open PostgreSQL: %v", err)
	}
	db.SetMaxOpenConns(2)
	t.Cleanup(func() { _ = db.Close() })
	ctx := context.Background()
	baseSchema := `
		CREATE TABLE IF NOT EXISTS Users (UserID text PRIMARY KEY, Name text NOT NULL, Role text NOT NULL, Email text NOT NULL, PasswordHash text NOT NULL, ClassroomID text);
		CREATE TABLE IF NOT EXISTS Classrooms (ID text PRIMARY KEY, Name text NOT NULL, TeacherID text);
		CREATE TABLE IF NOT EXISTS Transactions (TransactionID integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, UserID text NOT NULL, Amount integer NOT NULL, Timestamp timestamptz NOT NULL, Description text NOT NULL);
		CREATE TABLE IF NOT EXISTS ManualCoinAdjustments (UserID text PRIMARY KEY, Amount integer NOT NULL DEFAULT 0);
		CREATE TABLE IF NOT EXISTS ClassroomMemberships (ClassroomID text NOT NULL, UserID text NOT NULL, MembershipRole text NOT NULL, IsPrimary boolean NOT NULL DEFAULT false, Active boolean NOT NULL DEFAULT true, Source text NOT NULL DEFAULT 'local', UpdatedAt timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (ClassroomID, UserID, MembershipRole));`
	if _, err := db.ExecContext(ctx, baseSchema); err != nil {
		t.Fatalf("create prize prerequisites: %v", err)
	}
	migration, err := os.ReadFile(filepath.Join("..", "..", "Seed_DataBase5.sql"))
	if err != nil {
		t.Fatalf("read migration: %v", err)
	}
	for attempt := 1; attempt <= 2; attempt++ {
		if _, err := db.ExecContext(ctx, string(migration)); err != nil {
			t.Fatalf("apply migration attempt %d: %v", attempt, err)
		}
	}
	if _, err := db.ExecContext(ctx, `
		INSERT INTO Users (UserID,Name,Role,Email,PasswordHash,ClassroomID) VALUES
		('prize-student','Prize Student','student','student-prize@example.com','hash','prize-class'),
		('prize-teacher','Prize Teacher','teacher','teacher-prize@example.com','hash',NULL)
		ON CONFLICT (UserID) DO UPDATE SET Name=EXCLUDED.Name, Role=EXCLUDED.Role, Email=EXCLUDED.Email, ClassroomID=EXCLUDED.ClassroomID;
		INSERT INTO Classrooms (ID,Name,TeacherID) VALUES ('prize-class','Prize Class','prize-teacher') ON CONFLICT (ID) DO UPDATE SET Name=EXCLUDED.Name;
		INSERT INTO ClassroomMemberships (ClassroomID,UserID,MembershipRole,IsPrimary,Active) VALUES
		('prize-class','prize-student','student',true,true),('prize-class','prize-teacher','teacher',true,true)
		ON CONFLICT (ClassroomID,UserID,MembershipRole) DO UPDATE SET Active=true;`); err != nil {
		t.Fatalf("seed prize lifecycle: %v", err)
	}

	store := NewSQLStore(db)
	stock := 1
	prizeID, err := store.CreateClassroomPrize(ctx, "prize-teacher", domain.PrizeInput{ClassroomID: "prize-class", Name: "Apple Snack", Emoji: "🍎", CoinPrice: 5, AvailableStock: &stock, Active: true})
	if err != nil {
		t.Fatalf("CreateClassroomPrize: %v", err)
	}
	purchasedAt := time.Date(2026, 8, 2, 15, 0, 0, 0, time.UTC)
	redemption, err := store.PurchaseClassroomPrize(ctx, "prize-student", prizeID, purchasedAt)
	if err != nil {
		t.Fatalf("PurchaseClassroomPrize: %v", err)
	}
	var remaining, notifications int
	if err := db.QueryRowContext(ctx, `SELECT AvailableStock FROM ClassroomPrizes WHERE PrizeID=$1`, prizeID).Scan(&remaining); err != nil || remaining != 0 {
		t.Fatalf("remaining stock = %d, %v", remaining, err)
	}
	if err := db.QueryRowContext(ctx, `SELECT COUNT(*) FROM PrizeNotificationOutbox WHERE RedemptionID=$1`, redemption.ID).Scan(&notifications); err != nil || notifications != 1 {
		t.Fatalf("notifications = %d, %v", notifications, err)
	}
	if err := store.CancelPrizeRedemption(ctx, "prize-teacher", redemption.ID, purchasedAt.Add(time.Minute)); err != nil {
		t.Fatalf("CancelPrizeRedemption: %v", err)
	}
	state, err := store.LoadStudentPrizeState(ctx, "prize-student")
	if err != nil {
		t.Fatalf("LoadStudentPrizeState: %v", err)
	}
	if state.CoinBalance != startingStudentCoins {
		t.Fatalf("balance after refund = %d, want %d", state.CoinBalance, startingStudentCoins)
	}
	if err := db.QueryRowContext(ctx, `SELECT AvailableStock FROM ClassroomPrizes WHERE PrizeID=$1`, prizeID).Scan(&remaining); err != nil || remaining != 1 {
		t.Fatalf("restored stock = %d, %v", remaining, err)
	}

	second, err := store.PurchaseClassroomPrize(ctx, "prize-student", prizeID, purchasedAt.Add(2*time.Minute))
	if err != nil {
		t.Fatalf("repeat purchase: %v", err)
	}
	if err := store.FulfillPrizeRedemption(ctx, "prize-teacher", second.ID, purchasedAt.Add(3*time.Minute)); err != nil {
		t.Fatalf("FulfillPrizeRedemption: %v", err)
	}
	if err := store.CancelPrizeRedemption(ctx, "prize-teacher", second.ID, purchasedAt.Add(4*time.Minute)); !errors.Is(err, ErrPrizeRedemptionNotPending) {
		t.Fatalf("cancel fulfilled error = %v", err)
	}
}

func TestPostgresUserAndClassroomLifecycle(t *testing.T) {
	databaseURL := os.Getenv("TEST_DATABASE_URL")
	if databaseURL == "" {
		t.Skip("TEST_DATABASE_URL is not configured")
	}

	db, err := sql.Open("postgres", databaseURL)
	if err != nil {
		t.Fatalf("open PostgreSQL: %v", err)
	}
	db.SetMaxOpenConns(1)
	t.Cleanup(func() { _ = db.Close() })
	if err := db.PingContext(context.Background()); err != nil {
		t.Fatalf("ping PostgreSQL: %v", err)
	}

	createPostgresTestSchema(t, db)
	store := NewSQLStore(db)
	ctx := context.Background()
	if _, err := db.ExecContext(ctx, `INSERT INTO Classrooms (ID, Name, TeacherID) VALUES ('seed-class', 'Seed Class', '')`); err != nil {
		t.Fatalf("seed classroom: %v", err)
	}

	student := domain.User{
		UserID: "integration-student", Name: "Integration Student", Role: "student",
		Email: "integration.student@example.com", PasswordHash: "hash", ClassroomID: "seed-class",
	}
	if err := store.CreateStudent(ctx, student); err != nil {
		t.Fatalf("CreateStudent: %v", err)
	}
	loaded, err := store.FindUserByEmail(ctx, student.Email)
	if err != nil {
		t.Fatalf("FindUserByEmail: %v", err)
	}
	if loaded.UserID != student.UserID || loaded.ClassroomID != "seed-class" {
		t.Fatalf("loaded student = %#v", loaded)
	}
	if err := store.CreateStudent(ctx, student); !errors.Is(err, ErrUserAlreadyExists) {
		t.Fatalf("duplicate CreateStudent error = %v, want ErrUserAlreadyExists", err)
	}

	missing := student
	missing.UserID = "rolled-back-student"
	missing.Email = "rolled.back@example.com"
	missing.ClassroomID = "missing-class"
	if err := store.CreateStudent(ctx, missing); !errors.Is(err, ErrClassroomNotFound) {
		t.Fatalf("missing classroom error = %v, want ErrClassroomNotFound", err)
	}
	var rolledBackCount int
	if err := db.QueryRowContext(ctx, `SELECT COUNT(*) FROM Users WHERE UserID = $1`, missing.UserID).Scan(&rolledBackCount); err != nil {
		t.Fatalf("check rollback: %v", err)
	}
	if rolledBackCount != 0 {
		t.Fatal("failed CreateStudent persisted a user")
	}

	teacher := domain.User{UserID: "integration-teacher", Name: "Integration Teacher", Role: "teacher", Email: "teacher@example.com", PasswordHash: "hash"}
	if err := store.CreateTeacher(ctx, teacher); err != nil {
		t.Fatalf("CreateTeacher: %v", err)
	}
	classroom := domain.Classroom{
		ID: "integration-class", Name: "Integration Class", TeacherID: teacher.UserID,
		StudentIDs: []string{student.UserID},
	}
	if err := store.CreateClassroom(ctx, classroom); err != nil {
		t.Fatalf("CreateClassroom: %v", err)
	}
	classrooms, err := store.ListClassrooms(ctx)
	if err != nil {
		t.Fatalf("ListClassrooms: %v", err)
	}
	found := false
	for _, item := range classrooms {
		if item.ID == classroom.ID {
			found = item.TeacherID == teacher.UserID && len(item.StudentIDs) == 1 && item.StudentIDs[0] == student.UserID
		}
	}
	if !found {
		t.Fatalf("ListClassrooms did not return normalized roster: %#v", classrooms)
	}
}

func createPostgresTestSchema(t *testing.T, db *sql.DB) {
	t.Helper()
	const schema = `
		CREATE TEMP TABLE Users (
			UserID text PRIMARY KEY, Name text NOT NULL, Role text NOT NULL,
			Email text NOT NULL, PasswordHash text NOT NULL, ClassroomID text
		);
		CREATE TEMP TABLE Classrooms (
			ID text PRIMARY KEY, Name text NOT NULL, TeacherID text
		);
		CREATE TEMP TABLE ClassroomStudents (
			ClassroomID text NOT NULL, StudentID text NOT NULL,
			PRIMARY KEY (ClassroomID, StudentID)
		);
		CREATE TEMP TABLE ClassroomMemberships (
			ClassroomID text NOT NULL, UserID text NOT NULL, MembershipRole text NOT NULL,
			IsPrimary boolean NOT NULL DEFAULT false, Active boolean NOT NULL DEFAULT true,
			Source text NOT NULL DEFAULT 'local', UpdatedAt timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
			PRIMARY KEY (ClassroomID, UserID, MembershipRole)
		);
		CREATE TEMP TABLE IntegrationConnections (
			IntegrationConnectionID bigint PRIMARY KEY, ProviderKind text NOT NULL
		);
		CREATE TEMP TABLE ExternalEntityMappings (
			IntegrationConnectionID bigint NOT NULL, EntityKind text NOT NULL,
			LocalID text NOT NULL, Active boolean NOT NULL DEFAULT true,
			UpdatedAt timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
		);`
	if _, err := db.Exec(schema); err != nil {
		t.Fatalf("create temporary PostgreSQL schema: %v", err)
	}
}
